runtime: python39
instance_class: F2
env_variables:
  PORT: "8080"

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  
entrypoint: gunicorn -b :$PORT src.app:app
