version: '3'

services:
  glove-speed-tracker:
    build: .
    container_name: glove-speed-tracker
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  # Uncomment the following section to add a reverse proxy if needed
  # nginx:
  #   image: nginx:alpine
  #   container_name: glove-speed-tracker-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - glove-speed-tracker
  #   restart: unless-stopped
